server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/duks-coffee
    username: pruebasv2
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect